export const pagesLink = {
  home: '/',
  ships: '/ships',
  routes: '/routes',
  search: '/search',
  blog: '/blog',
  privacy: '/privacy',
  contacts: '/contacts',
  sale: '/sale',
  info: '/info',
  about: '/about',
  russiaRiver: '/pages/russian-river',
  sea: '/pages/sea',
  expedition: '/pages/expedition',
  cruise2024: '/pages/cruise2024',
};
