export const pagesLink = {
  home: '/',
  ships: '/ships',
  routes: '/routes',
  search: '/search',
  blog: '/blog',
  privacy: '/privacy',
  contacts: '/contacts',
  sale: '/sale',
  info: '/info',
  about: '/about',
  russiaRiver: '/russia-river',
  sea: '/pages/sea',
  expedition: '/expedition',
  cruise2024: '/cruise2024',
  cruise2025: '/cruise2025',
  detiBesplatno: '/deti-besplatno',
  pirogov: '/general/pirogov',
  pensioneram: '/pensioneram',
  ranneeBronirovanie: '/rannee-bronirovanie',
  lygotnyeSkidki: '/lygotnye-skidki',
  godovshina: '/godovshina',
  molodojenam: '/molodojenam',
  postoyannymKlientam: '/molodpostoyannym-klientam',
  gruppam: '/gruppam',
};
